ED-94 added block level filter
shikshalokam/ml-reports-service pull request #72
Opened 2023-01-10 11:14 UTC by ankitpws

Added Block level filter and we have to add two env variable.

2023-01-24 12:44 UTC, aks30 requested changes
Reviewed and added comments on 24 Jan

2023-01-24 12:44 UTC, aks30 commented on controllers/v1/resource.js
> +                if(getDistict || getOrganisation){
@ankitpws - Please optimise the code and write comments everywhere possible

2023-01-24 12:44 UTC, aks30 commented on controllers/v1/resource.js
> +            if(req.query.resourceType == ResourceType.SOLUTION){
@ankitpws  - Please optimize the code and write comments everywhere possible

2023-01-24 12:44 UTC, aks30 commented on helper/resource.js
> +            if(req.query.resourceType == ResourceType.SOLUTION) {
@ankitpws Please optimise this code, use ternary operator where possible and put comments.

2023-01-24 12:44 UTC, aks30 commented on helper/resource.js
> +            console.log({druidConnection: options});
@ankitpws please remove this

2023-01-24 12:44 UTC, aks30 commented on helper/resource.js
> +            if(req.query.resourceType == ResourceType.SOLUTION) {
@ankitpws Please optimize this code, use the ternary operator where possible, and put comments.

2023-01-24 12:44 UTC, aks30 commented on helper/resource.js
> +exports.getBlocks = async function(req,res){
@ankitpws Please optimize this code, use the ternary operator where possible, and put comments. Also remove console logs.

2023-01-24 12:44 UTC, aks30 commented on controllers/v1/resource.js
> +exports.filtervalues = async function (req, res) {
@ankitpws - Remove the current ml core service API, and remove the API from KONG i.e. modify the API endpoint and downstream URL

2023-01-24 12:44 UTC, aks30 commented on controllers/v1/resource.js
> +exports.filtervalues = async function (req, res) {
Also remove related functionality from code.

2023-01-24 12:47 UTC, aks30 commented on controllers/v1/resource.js
> +exports.filtervalues = async function (req, res) {
@ankitpws Check if the current ML Core API does role and program level access check before returning these results. If yes, we should do it here as well.

2023-02-22 09:27 UTC, VISHNUDAS-tunerlabs commented on helper/kendra_service.js
> +    console.log({ 'CoreServiceUserExtensionUrl: ': url });
@ankitpws pls remove the console if its not required

2023-02-22 09:30 UTC, VISHNUDAS-tunerlabs commented on helper/resource.js
> +        try {
@ankitpws can you please add comments for better understanding

2023-04-07 09:04 UTC, aks30 requested changes
Reviewed on 7 April

2023-04-07 09:04 UTC, aks30 commented on helper/resource.js
> +const { ResourceType } = require("../common/enum.utils");
@ankitpws - Please add basic info at the beginning of the file similar to other services.

2023-04-10 10:27 UTC, aks30 requested changes
Reviewed on 10 April

2023-04-10 10:27 UTC, aks30 commented on common/enum.utils.js
> +exports.ResourceTypeProjection = {
@ankitpws - Please add comments on the top what this file is used for etc

2023-04-10 10:27 UTC, aks30 commented on .env.sample
> +SURVEY_RESOURCE_DATASOURCE_NAME = "SURVEY_RESOURCE_DATASOURCE_NAME"   // Solution resource data source name
@ankitpws Comments can be proper to convey the type of solution etc

2023-04-10 10:27 UTC, aks30 commented on common/druid_queries.json
> +    "solution_distric_level_query": {"queryType": "groupBy","dataSource": "ml-project-status","dimensions": ["district_name", "district_externalId"],"granularity": "all","intervals": "1901-01-01T00:0
@ankitpws using ml-project-status might not be a good idea here. It will be misleading

2023-04-10 10:27 UTC, aks30 commented on controllers/v1/resource.js
> +        }else{
@ankitpws indentation and spacing should be consistent

2023-04-10 10:27 UTC, aks30 commented on controllers/v1/resource.js
> +    const userExtension = await resourceHelper.userExtensions(req,res);
@ankitpws - Please the add comments about this function and what it does.

2023-04-10 10:27 UTC, aks30 commented on helper/resource.js
> +                for(let platformCode = 0; platformCode < userExtensions.result.platformRoles.length; platformCode++){
@ankitpws Should we not validate if the user has the given role for the program id given in request param?

2023-04-10 10:27 UTC, aks30 commented on helper/resource.js
> +                bodyParam.dataSource  = req.body.solutionType === SolutionType.PROJECT ? process.env.PROJECT_RESOURCE_DATASOURCE_NAME : req.body.solutionType === SolutionType.OBSERVATION ? process.en
@ankitpws All the places where this is used we can have one common function

2023-04-10 14:47 UTC, aks30 requested changes
Reviewed on 10 April

2023-04-10 14:47 UTC, aks30 commented on .env.sample
> +PROJECT_RESOURCE_DATASOURCE_NAME = "PROJECT_RESOURCE_DATASOURCE_NAME"   // project resource data source name
@ankitpws In comment P has to be capital same for all below

2023-04-10 14:47 UTC, aks30 commented on common/enum.utils.js
> + * name : enum.utils.js
@ankitpws This is not really enum, why are we calling it so? can be just constant like other services.

2023-04-10 14:47 UTC, aks30 commented on common/utils.js
> +    dataSource  = body.solutionType === SolutionType.PROJECT ? process.env.PROJECT_RESOURCE_DATASOURCE_NAME : body.solutionType === SolutionType.OBSERVATION ? process.env.OBSERVATION_RESOURCE_DATASOU
@ankitpws Please use switch case, code should be readable

2023-04-10 14:47 UTC, aks30 commented on helper/resource.js
> +                const result = data.map(district => ({ id: district.event.organisation_id, name: district.event.organisation_name }));
@ankitpws why is this district?

2023-04-10 14:47 UTC, aks30 commented on helper/resource.js
> +                const result = data.map(district => ({ id: req.query.resourceType == ResourceType.SOLUTION ? district.event.district_externalId : district.event.district_id, name: district.event.dist
In a given call, req.query.resourceType will be fixed then why for a given result in map in loop we should check the same

2023-04-10 14:47 UTC, aks30 commented on helper/resource.js
> +                const result = data.map(block => ({ id: req.query.resourceType == ResourceType.SOLUTION ? block.event.block_externalId : block.event.block_id, name: block.event.block_name }));
@ankitpws we can avoid checking in loop the same if condition. Also why we need for solution external id and for program the block id? What is the reason

2023-04-11 12:00 UTC, aks30 approved these changes
Approved

2023-04-11 12:00 UTC, merged